name: pyna_preprocessing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scipy
  - pyyaml
  - pip:
    - pynapple==0.10.1
    - nwbmatic==0.1.2
